version: '3'
services:
  canvas:
    image: lbjay/canvas-docker
    ports:
      - "3000:3000"
    logging:
      driver: none
  db:
    build:
        context: .
        dockerfile: Dockerfile.db
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: docker
  wdb:
    image: kozea/wdb-server
    ports:
      - "1984:1984"
  redis:
    image: redis:alpine
  web:
    image: peerfeedback.web
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    volumes:
      - ./:/opt/
    links:
      - canvas
      - db
      - wdb
      - redis
  worker:
    image: peerfeedback.web
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - PYTHONUNBUFFERED=TRUE
      - ENV=dev
    volumes:
      - ./:/opt/
    command: flask rq worker --logging_level=DEBUG
    links:
      - redis
    depends_on:
      - redis
  scheduler:
    image: peerfeedback.web
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./:/opt/
    command: flask rq scheduler
    links:
      - redis
    depends_on:
      - redis
