"""add assignment attributes to tasks

Revision ID: 03e62dbc3d7c
Revises: 630dc3eaffe2
Create Date: 2018-03-24 12:16:06.919056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03e62dbc3d7c'
down_revision = '630dc3eaffe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('assignment_description', sa.Text(), nullable=True))
    op.add_column('task', sa.Column('assignment_name', sa.Text(), nullable=True))
    op.add_column('task', sa.Column('partner_avatar', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'partner_avatar')
    op.drop_column('task', 'assignment_name')
    op.drop_column('task', 'assignment_description')
    # ### end Alembic commands ###
