"""add name to user model

Revision ID: 04a23a3ba3e7
Revises: 1498d3a2a6b9
Create Date: 2018-04-07 15:45:51.497458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a23a3ba3e7'
down_revision = '1498d3a2a6b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'draft', 'pairing', ['pairing_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_constraint(None, 'draft', type_='foreignkey')
    # ### end Alembic commands ###
