"""adds use_rubric flag to assignment settings

Revision ID: 0679b70b4a3e
Revises: e0bdd77b83f2
Create Date: 2018-05-01 15:14:12.676462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0679b70b4a3e'
down_revision = 'e0bdd77b83f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_settings', sa.Column('use_rubric', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment_settings', 'use_rubric')
    # ### end Alembic commands ###
