"""adds user settings

Revision ID: 2f4bc1bcaf32
Revises: 84090d13b5fd
Create Date: 2018-05-28 05:50:26.455951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f4bc1bcaf32'
down_revision = '84090d13b5fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_emails', sa.Boolean(), nullable=True),
    sa.Column('feedback_emails', sa.Boolean(), nullable=True),
    sa.Column('discussion_emails', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
