"""adds pdf filter to assignment settings

Revision ID: 372399cf6c79
Revises: 05fe3253e9f4
Create Date: 2019-10-02 04:37:41.120033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372399cf6c79'
down_revision = '05fe3253e9f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_settings', sa.Column('filter_pdf', sa.Boolean(), server_default='f', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment_settings', 'filter_pdf')
    # ### end Alembic commands ###
