"""adds course_id to Pairing

Revision ID: 3850eb9e4c2a
Revises: 9a658b90b200
Create Date: 2018-03-30 17:01:51.660541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3850eb9e4c2a'
down_revision = '9a658b90b200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pairing', sa.Column('course_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pairing', 'course_id')
    # ### end Alembic commands ###
