"""added feedback relationship to task

Revision ID: 3eaa8543a1b2
Revises: b6ef8a64e190
Create Date: 2018-04-04 16:14:27.927913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eaa8543a1b2'
down_revision = 'b6ef8a64e190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('feedback_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'feedback', ['feedback_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'feedback_id')
    # ### end Alembic commands ###
