"""adds user reputation fields

Revision ID: 46f2d8a75ddf
Revises: 371a2ccc69e9
Create Date: 2019-10-21 09:20:46.882648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46f2d8a75ddf'
down_revision = '371a2ccc69e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('feedback_given', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('oldest_review', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('reputation', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reputation')
    op.drop_column('users', 'oldest_review')
    op.drop_column('users', 'feedback_given')
    # ### end Alembic commands ###
