"""adds backrefs for model orm

Revision ID: 630dc3eaffe2
Revises: 336a1790e761
Create Date: 2018-03-22 05:44:20.980137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '630dc3eaffe2'
down_revision = '336a1790e761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('draft', sa.Column('pairing_id', sa.Integer(), nullable=True))
    op.drop_constraint('draft_pairing_fkey', 'draft', type_='foreignkey')
    op.drop_constraint('draft_owner_fkey', 'draft', type_='foreignkey')
    op.create_foreign_key(None, 'draft', 'pairing', ['pairing_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'draft', 'users', ['owner_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('draft', 'pairing')
    op.drop_column('draft', 'owner')
    op.add_column('feedback', sa.Column('assignment_id', sa.Integer(), nullable=True))
    op.add_column('feedback', sa.Column('pairing_id', sa.Integer(), nullable=True))
    op.drop_constraint('feedback_pairing_fkey', 'feedback', type_='foreignkey')
    op.drop_constraint('feedback_assignment_fkey', 'feedback', type_='foreignkey')
    op.create_foreign_key(None, 'feedback', 'pairing', ['pairing_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'feedback', 'assignment', ['assignment_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('feedback', 'pairing')
    op.drop_column('feedback', 'assignment')
    op.add_column('pairing', sa.Column('assignment_id', sa.Integer(), nullable=False))
    op.add_column('pairing', sa.Column('grader_id', sa.Integer(), nullable=True))
    op.add_column('pairing', sa.Column('recipient_id', sa.Integer(), nullable=False))
    op.drop_constraint('pairing_grader_fkey', 'pairing', type_='foreignkey')
    op.drop_constraint('pairing_recipient_fkey', 'pairing', type_='foreignkey')
    op.drop_constraint('pairing_assignment_fkey', 'pairing', type_='foreignkey')
    op.create_foreign_key(None, 'pairing', 'assignment', ['assignment_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'pairing', 'users', ['grader_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'pairing', 'users', ['recipient_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_column('pairing', 'grader')
    op.drop_column('pairing', 'assignment')
    op.drop_column('pairing', 'recipient')
    op.add_column('task', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('pairing_id', sa.Integer(), nullable=True))
    op.drop_constraint('task_assignee_fkey', 'task', type_='foreignkey')
    op.drop_constraint('task_pairing_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'pairing', ['pairing_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'task', 'users', ['owner_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('task', 'pairing')
    op.drop_column('task', 'assignee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('assignee', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('pairing', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_pairing_fkey', 'task', 'pairing', ['pairing'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key('task_assignee_fkey', 'task', 'users', ['assignee'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('task', 'pairing_id')
    op.drop_column('task', 'owner_id')
    op.add_column('pairing', sa.Column('recipient', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('pairing', sa.Column('assignment', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('pairing', sa.Column('grader', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pairing', type_='foreignkey')
    op.drop_constraint(None, 'pairing', type_='foreignkey')
    op.drop_constraint(None, 'pairing', type_='foreignkey')
    op.create_foreign_key('pairing_assignment_fkey', 'pairing', 'assignment', ['assignment'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('pairing_recipient_fkey', 'pairing', 'users', ['recipient'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key('pairing_grader_fkey', 'pairing', 'users', ['grader'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_column('pairing', 'recipient_id')
    op.drop_column('pairing', 'grader_id')
    op.drop_column('pairing', 'assignment_id')
    op.add_column('feedback', sa.Column('assignment', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('feedback', sa.Column('pairing', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.create_foreign_key('feedback_assignment_fkey', 'feedback', 'assignment', ['assignment'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('feedback_pairing_fkey', 'feedback', 'pairing', ['pairing'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('feedback', 'pairing_id')
    op.drop_column('feedback', 'assignment_id')
    op.add_column('draft', sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('draft', sa.Column('pairing', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'draft', type_='foreignkey')
    op.drop_constraint(None, 'draft', type_='foreignkey')
    op.create_foreign_key('draft_owner_fkey', 'draft', 'users', ['owner'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('draft_pairing_fkey', 'draft', 'pairing', ['pairing'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_column('draft', 'pairing_id')
    op.drop_column('draft', 'owner_id')
    # ### end Alembic commands ###
