"""adds deadline date as integer

Revision ID: 835fea7fd9d7
Revises: e0464eb87ede
Create Date: 2018-08-16 10:53:05.738573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835fea7fd9d7'
down_revision = 'e0464eb87ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_settings', sa.Column('feedback_deadline', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment_settings', 'feedback_deadline')
    # ### end Alembic commands ###
