"""add grades to feedback and draft

Revision ID: 8a28b3f24741
Revises: d5ff5c719c0b
Create Date: 2018-04-13 13:34:44.801323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a28b3f24741'
down_revision = 'd5ff5c719c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft', sa.Column('grades', sa.JSON(), nullable=True))
    op.add_column('feedback', sa.Column('grades', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'grades')
    op.drop_column('draft', 'grades')
    # ### end Alembic commands ###
