"""removed assignment model

Revision ID: 9a658b90b200
Revises: 03e62dbc3d7c
Create Date: 2018-03-25 13:08:27.787484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a658b90b200'
down_revision = '03e62dbc3d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('feedback_assignment_id_fkey', 'feedback', type_='foreignkey')
    op.alter_column('pairing', 'assignment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('pairing_assignment_id_fkey', 'pairing', type_='foreignkey')
    op.add_column('task', sa.Column('assignment_id', sa.Integer(), nullable=True))
    op.drop_table('assignment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
    sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('canvas_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='assignment_pkey')
    )
    op.drop_column('task', 'assignment_id')
    op.create_foreign_key('pairing_assignment_id_fkey', 'pairing', 'assignment', ['assignment_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('pairing', 'assignment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key('feedback_assignment_id_fkey', 'feedback', 'assignment', ['assignment_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
