"""adds course_id to assignment settings

Revision ID: 9d32d0637d6b
Revises: 835fea7fd9d7
Create Date: 2018-08-22 02:26:26.319379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d32d0637d6b'
down_revision = '835fea7fd9d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_settings', sa.Column('course_id', sa.Integer(), nullable=False))
    op.alter_column('assignment_settings', 'canvas_id', new_column_name='assignment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignment_settings', 'assignment_id', new_column_name='canvas_id')
    op.drop_column('assignment_settings', 'course_id')
    # ### end Alembic commands ###
