"""added receiver to the feedback

Revision ID: 9d902449819d
Revises: 2a4976a3c46c
Create Date: 2018-04-20 13:32:15.440539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d902449819d'
down_revision = '2a4976a3c46c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_feedback_receiver_id', 'feedback', 'users', ['receiver_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_feedback_receiver_id', 'feedback', type_='foreignkey')
    op.drop_column('feedback', 'receiver_id')
    # ### end Alembic commands ###
