"""adds active flag to rubric

Revision ID: a2cb6e67e929
Revises: 4b85cfb810f3
Create Date: 2018-11-29 06:14:52.132294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2cb6e67e929'
down_revision = '4b85cfb810f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rubric', sa.Column('active', sa.Boolean(), nullable=True))
    op.execute('UPDATE rubric SET active=TRUE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rubric', 'active')
    # ### end Alembic commands ###
