"""adds submission warning flag

Revision ID: a73f14ec29ca
Revises: 46f2d8a75ddf
Create Date: 2020-06-20 13:19:01.921675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73f14ec29ca'
down_revision = '46f2d8a75ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('submission_warning', sa.Boolean(), server_default='t', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'submission_warning')
    # ### end Alembic commands ###
