"""refactored db design

Revision ID: b0a75081ac85
Revises: 3eaa8543a1b2
Create Date: 2018-04-05 17:57:56.433549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0a75081ac85'
down_revision = '3eaa8543a1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft', sa.Column('submission_id', sa.Integer(), nullable=True))
    op.drop_constraint('draft_pairing_id_fkey', 'draft', type_='foreignkey')
    op.drop_column('draft', 'owner_id')
    op.add_column('feedback', sa.Column('submission_id', sa.Integer(), nullable=True))
    op.drop_column('feedback', 'assignment_id')
    op.add_column('task', sa.Column('action_item_id', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('action_item_type', sa.String(length=30), nullable=True))
    op.drop_constraint('task_feedback_id_fkey', 'task', type_='foreignkey')
    op.drop_constraint('task_pairing_id_fkey', 'task', type_='foreignkey')
    op.drop_column('task', 'assignment_description')
    op.drop_column('task', 'pairing_id')
    op.drop_column('task', 'assignment_name')
    op.drop_column('task', 'feedback_id')
    op.drop_column('task', 'partner_avatar')
    op.drop_column('task', 'assignment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('assignment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('partner_avatar', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('feedback_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('assignment_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('pairing_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('assignment_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key('task_pairing_id_fkey', 'task', 'pairing', ['pairing_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key('task_feedback_id_fkey', 'task', 'feedback', ['feedback_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_column('task', 'action_item_type')
    op.drop_column('task', 'action_item_id')
    op.add_column('feedback', sa.Column('assignment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('feedback', 'submission_id')
    op.add_column('draft', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('draft_owner_id_fkey', 'draft', 'users', ['owner_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('draft', 'submission_id')
    # ### end Alembic commands ###
