"""adds feedback deadline to assignment settings

Revision ID: b0bc280b753e
Revises: ea8f062cef39
Create Date: 2018-08-03 05:41:56.993268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0bc280b753e'
down_revision = 'ea8f062cef39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_settings', sa.Column('feedback_deadline', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment_settings', 'feedback_deadline')
    # ### end Alembic commands ###
