"""adds custom deadline to assignments

Revision ID: c9ed9873b5b2
Revises: df9fcb69dec0
Create Date: 2019-08-10 15:44:10.605405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9ed9873b5b2'
down_revision = 'df9fcb69dec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_settings', sa.Column('custom_deadline', sa.DateTime(), nullable=True))
    op.add_column('assignment_settings', sa.Column('deadline_format', sa.String(length=10), server_default='canvas', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment_settings', 'deadline_format')
    op.drop_column('assignment_settings', 'custom_deadline')
    # ### end Alembic commands ###
