"""add archived field to pairing

Revision ID: df9fcb69dec0
Revises: 2663570470a2
Create Date: 2019-08-01 14:13:09.748017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df9fcb69dec0'
down_revision = '2663570470a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pairing', sa.Column('archived', sa.Boolean(), server_default='f', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pairing', 'archived')
    # ### end Alembic commands ###
