"""adds assignment settings model

Revision ID: e1f49ada42b7
Revises: 0f3ae846b950
Create Date: 2018-04-11 15:04:57.490214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f49ada42b7'
down_revision = '0f3ae846b950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_settings',
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canvas_id', sa.Integer(), nullable=False),
    sa.Column('extra_reviews_allowed', sa.Boolean(), nullable=True),
    sa.Column('extra_reviews', sa.Integer(), nullable=True),
    sa.Column('rubric_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubric.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignment_settings')
    # ### end Alembic commands ###
