"""add course, reviewer details to feedback

Revision ID: ed750da520e6
Revises: 1a175f735dde
Create Date: 2018-04-15 17:31:57.494744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed750da520e6'
down_revision = '1a175f735dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('assignment_id', sa.Integer(), nullable=True))
    op.add_column('feedback', sa.Column('assignment_name', sa.String(length=150), nullable=True))
    op.add_column('feedback', sa.Column('course_id', sa.Integer(), nullable=True))
    op.add_column('feedback', sa.Column('course_name', sa.String(length=150), nullable=True))
    op.add_column('feedback', sa.Column('reviewer_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_feedback_reviewer', 'feedback', 'users', ['reviewer_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_feedback_reviewer', 'feedback', type_='foreignkey')
    op.drop_column('feedback', 'reviewer_id')
    op.drop_column('feedback', 'course_name')
    op.drop_column('feedback', 'course_id')
    op.drop_column('feedback', 'assignment_name')
    op.drop_column('feedback', 'assignment_id')
    # ### end Alembic commands ###
