"""adds course assignment names to comment

Revision ID: f3bdf314bf12
Revises: d080ed144e6b
Create Date: 2018-07-03 06:55:56.142038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3bdf314bf12'
down_revision = 'd080ed144e6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('assignment_name', sa.String(), nullable=True))
    op.add_column('comment', sa.Column('course_name', sa.String(), nullable=True))
    op.add_column('notification', sa.Column('recipient_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_notification_recipient_id', 'notification', 'users', ['recipient_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_notification_recipient_id', 'notification', type_='foreignkey')
    op.drop_column('notification', 'recipient_id')
    op.drop_column('comment', 'course_name')
    op.drop_column('comment', 'assignment_name')
    # ### end Alembic commands ###
