"""empty message

Revision ID: f4b2f8515c9c
Revises: c60000257f21
Create Date: 2018-02-28 01:32:31.720987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4b2f8515c9c'
down_revision = 'c60000257f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'password')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
