"""adds oauth fields to user model

Revision ID: f86a4aaaa12b
Revises: 76625036faa1
Create Date: 2018-03-09 04:40:15.101150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f86a4aaaa12b'
down_revision = '76625036faa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pairing', 'reviewRound')
    op.add_column('users', sa.Column('canvas_access_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('canvas_expiration_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('canvas_refresh_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'canvas_refresh_token')
    op.drop_column('users', 'canvas_expiration_time')
    op.drop_column('users', 'canvas_access_token')
    op.add_column('pairing', sa.Column('reviewRound', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
